# Generated by Django 3.1 on 2020-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_state',
            name='pin_no',
            field=models.IntegerField(default=1),
        ),
    ]
