# Generated by Django 3.1 on 2020-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pin_state_pin_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_state',
            name='schedule_status',
            field=models.BooleanField(default=False),
        ),
    ]
