# Generated by Django 3.1 on 2020-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pin_state_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_state',
            name='end_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin_state',
            name='end_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin_state',
            name='start_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin_state',
            name='start_min',
            field=models.IntegerField(default=0),
        ),
    ]
