# Generated by Django 3.1 on 2020-10-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201002_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_state',
            name='interrupt',
            field=models.BooleanField(default=False),
        ),
    ]
