# Generated by Django 3.1 on 2020-10-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pin_state_interrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_state',
            name='gac_toggler',
            field=models.BooleanField(default=False),
        ),
    ]
