# Generated by Django 3.1 on 2020-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201019_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin_state',
            name='bc_toggler',
        ),
        migrations.RemoveField(
            model_name='pin_state',
            name='gac_toggler',
        ),
        migrations.RemoveField(
            model_name='pin_state',
            name='sc_toggler',
        ),
        migrations.AddField(
            model_name='pin_state',
            name='toggler',
            field=models.CharField(default='bc', max_length=3),
        ),
    ]
