# Generated by Django 3.1 on 2020-10-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pin_state_hardware_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin_state',
            name='hardware_status',
        ),
    ]
