# Generated by Django 3.1 on 2020-10-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='name',
            field=models.CharField(default='default hardware', max_length=50),
            preserve_default=False,
        ),
    ]
