# Generated by Django 3.1 on 2020-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hardware_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
