# Generated by Django 3.1 on 2020-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201021_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='humid',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='temp',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
