# Generated by Django 3.1 on 2020-11-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201115_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_state',
            name='sensitive_action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pin_state',
            name='sensitive_temp',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='pin_state',
            name='temp_sensitivity_status',
            field=models.BooleanField(default=False),
        ),
    ]
